clear all;
close all;


acceptanceDtBe=[
%0.003    -14.503927   1.5e-3  99.74
%0.004    -14.502305   1.3e-3  99.61
0.005    -14.501368   1.2e-3  99.48
0.006    -14.501925   1.1e-3  99.33
0.007    -14.502326   1.0e-3  99.18
0.008    -14.501938   9.0e-4  99.02
0.009    -14.502018   9.0e-4  98.86
0.01     -14.503246   8.0e-4  98.69
];


dt = acceptanceDtBe(:,1);
E =  acceptanceDtBe(:,2); %%%%%%%%%% ACCEPTANCE


hE= plot(dt,E)

 
%%% Ajust line properties (functional)
set(hE(1)                            , ...
  'LineStyle'       , '-'      , ...
  'Marker'          , '.'         , ...
  'Color'           , [0 0 .5]  );

% 
% %%%% Adjust line properties (esthetics)
set(hE(1)                            , ...
  'LineWidth'       , 2           , ...
  'Marker'          , 'o'         , ...
  'MarkerSize'      , 6           , ...
  'MarkerEdgeColor' , [.2 .2 .2]  , ...
  'MarkerFaceColor' , [.7 .7 .7]  );


%%% Add legend and labels
hXLabel = xlabel('Time step, dt');
hYLabel = ylabel('Accepted moves, %');


%%% Add fonts and axis properties
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel, hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 14 );

set(gca, ...
  'Box'         , 'on'     , ...
  'TickDir'     , 'in'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );

%%%% limits
%  xlim([9e-5 1]);












%%%%hE=plot(dt,E)

%    plot(dt,E, 'r', 'LineWidth', 2);
%    
%   %%% Ajust line properties (functional)
%  set(hE(1)                            , ...
%    'LineStyle'       , 'none'      , ...
%    'Marker'          , '.'         , ...
%    'Color'           , [.3 .3 .3]  );
%  
%  % 
%  % %%%% Adjust line properties (esthetics)
%  set(hE(1)                            , ...
%    'LineWidth'       , 1           , ...
%    'Marker'          , 'o'         , ...
%    'MarkerSize'      , 6           , ...
%    'MarkerEdgeColor' , [.2 .2 .2]  , ...
%    'MarkerFaceColor' , [.7 .7 .7]  );
%  % 
%  % 
%  % % % % adjust error bar width
%  % hE_c  = ...
%  %     get(hE     , 'Children'    );
%  % errorbarXData          = ...
%  %     get(hE_c(2), 'XData'       );
%  % errorbarXData(4:9:end) = errorbarXData(1:9:end) - hodet;
%  % errorbarXData(7:9:end) = errorbarXData(1:9:end) - hodet;
%  % errorbarXData(5:9:end) = errorbarXData(1:9:end) + hodet;
%  % errorbarXData(8:9:end) = errorbarXData(1:9:end) + hodet;
%  % set(hE_c(2), 'XData', errorbarXData);
%  
%  
%  
%  %%% Add legend and labels
%  hXLabel = xlabel('Time step, dt');
%  hYLabel = ylabel('\% of accepted moves');
%  
%  
%  %%% Add fonts and axis properties
%  %  set( gca                       , ...
%  %     'FontName'   , 'Helvetica' );
%  %  set([hXLabel, hYLabel], ...
%  %     'FontName'   , 'AvantGarde');
%  %  set([hXLabel, hYLabel]  , ...
%  %     'FontSize'   , 14 );
%  %  
%  %  set(gca, ...
%  %   'Box'         , 'on'     , ...
%  %   'TickDir'     , 'in'     , ...
%  %   'TickLength'  , [.02 .02] , ...
%  %   'XMinorTick'  , 'on'      , ...
%  %   'YMinorTick'  , 'on'      , ...
%  %   'YGrid'       , 'on'      , ...
%  %   'XColor'      , [.3 .3 .3], ...
%  %   'YColor'      , [.3 .3 .3], ...
%  %   'XTick'       , xstick, ...
%  %   'YTick'       , ystick);
%  %  %   'LineWidth'   , 1         );
%  %  
%  
%  
